### ISSUE TITLE
Add the title ids that the bundled versions of welcome amiibo, please.

### ISSUE THREAD

**Issue by supernickyp** [RyDog199/ACNL-NTR-Cheats#26]
It its current state the plugin only works on welcome amiibo if you updated from the original ACNL. Not if you bought and downloaded the full welcome amiibo after its release.

**Comment by RyDog199** [comment]
I ruled this out because it's too time consuming for me to do it when the user can just download Animal Crossing straight from eShop / FreeShop / wherever they feel like downloading it.
Just passing the title ID of the Welcome Amiibo carts into the plugin won't make it, because the offsets are different, meaning the cheats won't work. 
If I wanted to make them work, it would require finding 100 offsets per each region.
